<a href="https://colab.research.google.com/github/lordWalnuts/hf-nlpCourse-notes/blob/main/hfChap2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers
from transformers import pipeline


In [ ]:
|from transformers import pipeline
from transformers import AutoTokenizer
from transformers import AutoModel

In [ ]:
classifier = pipeline("sentiment-analysis")
classifier(
     [
        "I've been waiting for a HuggingFace course my whole life.",
        "I hate this so much!",
    ]
)

In [ ]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [ ]:
raw_inputs =  [
     "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
]

inputs = tokenizer(raw_inputs,padding=True, truncation= True, return_tensors="pt")
inputs

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}

In [ ]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModel.from_pretrained(checkpoint)

Some weights of the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing DistilBertModel: ['classifier.weight', 'pre_classifier.weight', 'classifier.bias', 'pre_classifier.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
output = model(**inputs)
print(output.last_hidden_state.shape)


torch.Size([2, 16, 768])


In [ ]:
from transformers import AutoModelForSequenceClassification
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(**inputs)

In [ ]:
print(outputs.logits.shape)

NameError: ignored

In [ ]:
print(outputs.logits)

tensor([[-1.5607,  1.6123],
        [ 4.1692, -3.3464]], grad_fn=<AddmmBackward0>)


In [ ]:
import torch

preds = torch.nn.functional.softmax(outputs.logits,dim=-1)
print(preds)

tensor([[4.0195e-02, 9.5980e-01],
        [9.9946e-01, 5.4418e-04]], grad_fn=<SoftmaxBackward0>)


In [ ]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [ ]:
from transformers import AutoModelForMaskedLM

checkpoint = "distilbert-base-uncased"
model = AutoModelForMaskedLM.from_pretrained(checkpoint)

raw_input = [
    "This is a [MASK] of a young boy in a small town"
]

tknz = AutoTokenizer.from_pretrained(checkpoint)

inputs = tknz(raw_input, padding=True, truncation=True, return_tensors="pt")
print(inputs)

outputs = model(**inputs)
preds =  torch.nn.functional.softmax(outputs.logits,dim=-1)
print(preds)


{'input_ids': tensor([[ 101, 2023, 2003, 1037,  103, 1997, 1037, 2402, 2879, 1999, 1037, 2235,
         2237,  102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
tensor([[[4.2081e-07, 4.2520e-07, 4.3123e-07,  ..., 8.9260e-07,
          9.9892e-07, 6.3595e-06],
         [2.6272e-11, 2.9890e-11, 2.5417e-11,  ..., 5.4575e-11,
          1.1582e-10, 1.6809e-09],
         [3.4196e-13, 4.1341e-13, 3.4311e-13,  ..., 1.0457e-12,
          8.5916e-12, 2.3996e-11],
         ...,
         [2.7714e-13, 1.7881e-13, 2.5546e-13,  ..., 1.0201e-12,
          7.0469e-13, 6.9795e-13],
         [4.2736e-14, 3.2779e-14, 4.2346e-14,  ..., 2.4083e-13,
          1.3859e-13, 5.8581e-12],
         [2.2856e-14, 2.4643e-14, 2.5682e-14,  ..., 4.0568e-13,
          1.1801e-13, 9.9954e-13]]], grad_fn=<SoftmaxBackward0>)


In [ ]:
model.config.id2label


{0: 'LABEL_0', 1: 'LABEL_1'}

## Using HF Transformers

In [ ]:
from transformers import BertConfig, BertModel

config = BertConfig()
print(config)

model = BertModel(config)

BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.29.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}



In [ ]:
pretrained_config = BertModel.from_pretrained("bert-base-cased")
print(pretrained_config)

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(28996, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
  

In [ ]:
model.save_pretrained("/content/")

In [ ]:
!pwd

/content


In [ ]:
sequences = ["Hello!", "Cool.", "Nice!"]

from transformers import AutoTokenizer, PreTrainedTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
encoded_seq = tokenizer(sequences,padding=True,truncation=True)
print(encoded_seq['input_ids'])

[[101, 8667, 106, 102], [101, 13297, 119, 102], [101, 8835, 106, 102]]


In [ ]:
text = "Jim Morrison was the frontman for The Doors"
tkn_txt = text.split()
print(tkn_txt)

['Jim', 'Morrison', 'was', 'the', 'frontman', 'for', 'The', 'Doors']


In [ ]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

In [ ]:
tokenizer("Using a Transformer network is simple")

{'input_ids': [101, 7993, 170, 13809, 23763, 2443, 1110, 3014, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
sentences = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!"
]

checkpoint = "bert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
tokened_text = tokenizer.tokenize(sentences)
print(tokened_text)
ids = tokenizer.convert_tokens_to_ids(tokened_text)
print(ids)


['I', "'", 've', 'been', 'waiting', 'for', 'a', 'Hu', '##gging', '##F', '##ace', 'course', 'my', 'whole', 'life', '.', 'I', 'hate', 'this', 'so', 'much', '!']


In [ ]:
sequence = "Using a Transformer network is simple"
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)
print(ids)

[7993, 170, 13809, 23763, 2443, 1110, 3014]


In [ ]:
encoded_txt = tokenizer(sequence)
print(encoded_txt['input_ids'])

[101, 7993, 170, 13809, 23763, 2443, 1110, 3014, 102]


In [ ]:
decoded_string = tokenizer.decode([101])
print(decoded_string)

[CLS]




---



---




In [ ]:
import torch
from transformers import AutoModelForSequenceClassification

#download weights, configs and vocab
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
# initialize tokenizer
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
#init model
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for a HuggingFace course my whole life."
#tokenize
tkn = tokenizer.tokenize(sequence)
#convert to ids
ids = tokenizer.convert_tokens_to_ids(tkn)
#convert to pt tensors
input_ids = torch.tensor([ids])
print("Input IDs: ", input_ids)

output = model(input_ids)
print("Logits: ", output.logits)

Input IDs:  tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012]])
Logits:  tensor([[-2.7276,  2.8789]], grad_fn=<AddmmBackward0>)


In [ ]:
batch = [ids, ids]
input_batch = torch.tensor(batch)

print("Input IDs: ", input_batch)

output = model(input_ids)
print("Logits: ", output.logits)

Input IDs:  tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012],
        [ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012]])
Logits:  tensor([[-2.7276,  2.8789]], grad_fn=<AddmmBackward0>)


In [ ]:
from transformers import AutoModelForSequenceClassification

seq1_id =[[200,200,200]]
seq2_id = [[200,200]]

batched_id = [
    [200,200,200],
    [200,200,tokenizer.pad_token_id]
]

attention_mask = [
    [1,1,1],
    [1,1,0]
]

print(model(torch.tensor(seq1_id)).logits)
print(model(torch.tensor(seq2_id)).logits)
print(model(torch.tensor(batched_id),attention_mask=torch.tensor(attention_mask)).logits)



tensor([[ 1.5694, -1.3895]], grad_fn=<AddmmBackward0>)
tensor([[ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)
tensor([[ 1.5694, -1.3895],
        [ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)


In [ ]:
sentences = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!"
]

sen1_id = tokenizer.convert_tokens_to_ids(tokenizer.tokenize(sentences[0]))
sen2_id = tokenizer.convert_tokens_to_ids(tokenizer.tokenize(sentences[1]))

print(sen1_id)
print(sen2_id)

pid = tokenizer.pad_token_id

s1id = [101,1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102]
s2id = [1045, 5223, 2023, 2061, 2172, 999]

batched_seq = [
    [101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102],
    [1045, 5223, 2023, 206, pid, pid, pid, pid, pid, pid, pid, pid, pid, pid,pid,pid]
]    
  
attention_mask = [
    [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    [1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0]
]

output = model(torch.tensor(batched_seq),attention_mask=torch.tensor(attention_mask))
print(output.logits)

[1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012]
[1045, 5223, 2023, 2061, 2172, 999]
tensor([[-1.5607,  1.6123],
        [ 3.0844, -2.6190]], grad_fn=<AddmmBackward0>)


In [ ]:
sentences = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!"
]

from transformers import AutoModel,AutoModelForSequenceClassification, AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

input_ids = tokenizer(sentences, padding="longest", truncation=True, return_tensors='pt')
output = model(**input_ids)
print(output.logits)



tensor([[-1.5607,  1.6123],
        [ 4.1692, -3.3464]], grad_fn=<AddmmBackward0>)
